### ISSUE TITLE
Add a close 'X' button to the top right corner of the form in the sidebar

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/levantCarta#12]
This serves as a way to exit out of drawing/editing mode. For example,

When _editing_ an existing feature, this deselects the feature and jumps back to search in the sidebar. (Same behavior you currently have when clicking 'away' from a selected map feature.)

When _adding_ a new feature, this removes any incomplete geometry and attributes, jumps back to search, and exits drawing mode.

**Comment by DaviTeodoro** [comment]
solves it 6c8af56c582582d6e46286829edfafa31a19234d
