### ISSUE TITLE
Add in-line options to drawing tools when active

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/levantCarta#13]
These appear beside the given button in the toolbar when in drawing mode. For line and polygon, the options are "finish", "delete last point", and "cancel". For point, it's just "cancel".

Note: Unlike the close 'X' button at the top of the sidebar, which would remove a new feature that had not been completed and take you all the way out of drawing mode, here "cancel" just clears the incomplete drawing and keeps everything else the same.

**Comment by bcsheesley** [comment]
Here is an example screenshot:

![Screen Shot 2019-11-18 at 3 53 14 PM](https://user-images.githubusercontent.com/4501388/69097147-8f223580-0a1b-11ea-809d-1c92708057a2.png)

**Comment by davidheyman** [comment]
I think the undo button is a more straightforward solution here, assuming we can get it to undo point additions before the feature is created.
