### ISSUE TITLE
Remove the undo button

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/levantCarta#16]
I'm having a hard time remembering why we even need a separate undo button. We already have "remove last point" as an option while drawing, as well as the ability to delete any feature. I feel like we can simplify things and ditch it. @davidheyman do you have any thoughts on undo?

**Comment by bcsheesley** [comment]
On second thought, undo could come in handy when editing an existing feature. If we keep it, maybe we only undo edits made while a feature is selected. Once deselected, those changes are locked in and not undo-able any more.

**Comment by DaviTeodoro** [comment]
Related to #13

**Comment by davidheyman** [comment]
This is a really useful addition and definitely worth keeping. Just need to figure out the issue where the feature _create_ counts as a single action.

**Comment by DaviTeodoro** [comment]
we are almost there 
![Screen record from 2019-11-24 21 18 47](https://user-images.githubusercontent.com/11483241/69504429-80e38600-0f01-11ea-88bc-c4da8ac09563.gif)
