### ISSUE TITLE
Name attribute should NOT be required

### ISSUE THREAD

**Issue by davidheyman** [axismaps/levantCarta#2]

**Comment by DaviTeodoro** [comment]
properties.name can be null?

**Comment by davidheyman** [comment]
Correct. Some things don’t have specific names (like an urban extent) and other names aren’t known. On the map, a name is required for search and labeling, but not to draw.

**Comment by DaviTeodoro** [comment]
solved here b1a485b3bd843b18bd48f6c94c2990621f8070f6

**Comment by bcsheesley** [comment]
This is still being required in my testing, but only becomes outlined in red once I enter a Year or Type. If I'm reading this issue correctly, we should remove the red highlight, requirement text, and asterisk for Name.

![Screen Shot 2019-11-18 at 2 23 05 PM](https://user-images.githubusercontent.com/4501388/69091309-a529f900-0a0f-11ea-85e5-a701ba7b6852.png)

**Comment by bcsheesley** [comment]
@DaviTeodoro Oops, the online version https://condescending-poitras-8efc7d.netlify.com solved this. My bad. My local version must have gotten out of date.
