### ISSUE TITLE
Attribute fields should not be cleared when adding them before drawing their geometry

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/levantCarta#23]
When I add _all_ required fields and _then_ draw the feature, the attributes are saved. When I add _some_ required fields and then draw the feature, they are cleared.

I like how you allow attribute form editing and drawing to happen in any order for new features.

**Comment by DaviTeodoro** [comment]
theses 302c602db16724410b8edc9b6599018aadb3b11b 6304632f1872e060a48d23ef879f5a04b7c26d98 solve it
