### ISSUE TITLE
Feature should stay selected (orange) once drawn

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/levantCarta#25]
Please let me know if otherwise, but I don't think we need the state in which features are currently blue in color. So, in the example screenshot below, this line would remain as an orange dashed-line with nodes displayed after it is drawn.

![Screen Shot 2019-11-18 at 5 39 40 PM](https://user-images.githubusercontent.com/4501388/69103298-a3b9fa00-0a2a-11ea-9c38-1734f2fdd79e.png)

**Comment by DaviTeodoro** [comment]
This is related to #26

**Comment by DaviTeodoro** [comment]
This is related to #26
