### ISSUE TITLE
Make field names in data probe gray color

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/levantCarta#31]
![Screen Shot 2019-11-19 at 10 21 03 AM](https://user-images.githubusercontent.com/4501388/69164855-571c0080-0ab6-11ea-991f-1fb9676ab447.png)

**Comment by bcsheesley** [comment]
Don't worry about making the values left-aligned, like in that screenshot. I like the more condensed layout we have now.

**Comment by DaviTeodoro** [comment]
bad9cfc6fbb696215a5f00d2e0b3322b922c7c7e solves it
