### ISSUE TITLE
GeoJSON ID generated by client

### ISSUE THREAD

**Issue by davidheyman** [axismaps/levantCarta#5]
Are the ID's included in the GeoJSON guaranteed to be unique across the entire database? If so, I'll have the database trust what it gets sent. If not, I'll need to send back a new ID after the feature is created in the database.

**Comment by DaviTeodoro** [comment]
Hey Dave, they are using [hat() to generate the ids]( https://github.com/mapbox/mapbox-gl-draw/blob/f6bd479688af268cc78a5ade7e67277a9ef60461/src/feature_types/feature.js#L8). And taking a look at this issue https://github.com/substack/node-hat/issues/8 they we can see that these ids are not guaranteed to be unique.

**Comment by davidheyman** [comment]
Let’s use this library instead -> https://www.npmjs.com/package/uuid

Either v1 or v4 should work

**Comment by DaviTeodoro** [comment]
595ac2f6fef1f238d14a66f800815b3e8fb961ab solves it
