### ISSUE TITLE
Remove redundant select layer dropdown

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/levantCarta#56]
If we highlight the dropdown until a selection is made and add an up arrow, I think this becomes a little bit cleaner:

<img width="720" alt="dropdown" src="https://user-images.githubusercontent.com/4501388/122280827-36dd3f00-ceaf-11eb-9922-d1fd5cbeebc8.png">

**Comment by DaviTeodoro** [comment]
https://github.com/axismaps/levant-carta-next/commit/0f410d341a1b2e977ff1c4947229412e97e06609
