### ISSUE TITLE
Reduce line weights of features at lower zooms

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/levantCarta#59]
Just to prevent things from clumping up too much.

<img width="796" alt="roads" src="https://user-images.githubusercontent.com/4501388/122295667-1cab5d00-cebf-11eb-8389-d75ca764b633.png">

**Comment by DaviTeodoro** [comment]
https://github.com/axismaps/levant-carta-next/commit/8dea430e93e5bbace981262afaa25c04bd45f8b5
