### ISSUE TITLE
Automatically exit Split mode when the split is complete

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/levantCarta#68]
- Select a merged line feature
- Click the Split tool button
- The Split tool button appears active and there is no clear way to exit.

I don't think this one requires a mode change, like merge. It seems more like delete, which happens on press.

**Comment by DaviTeodoro** [comment]
To split a feature the user needs to select the part he wants to detach from the whole. The tool works in 3 steps from the user perpective: 
1- user selects the feature.
![image](https://user-images.githubusercontent.com/11483241/122594535-83568500-d03d-11eb-8628-8806ba53cd5b.png)
2- user clicks to split. 
3- user clicks the part he wants to detach. 
![image](https://user-images.githubusercontent.com/11483241/122594623-a123ea00-d03d-11eb-92fd-eace2c12db56.png)

I think what need to improve is the feedback on the second step. It is not clear that the user have to click again to select a part to detach.

**Comment by bcsheesley** [comment]
I that that's a good approach. Aside from some kind of text / tool-tip feedback, what about reducing the opacity of other features to zero when in split mode? This would focus attention on only those features that can be split. Maybe we can also use the same mouseover highlight from merge mode.

1 - Start
<img width="775" alt="1" src="https://user-images.githubusercontent.com/4501388/122602364-505dc280-d038-11eb-9b03-ef9d7e3fb46b.png">

2 - Select multipart feature
<img width="775" alt="2" src="https://user-images.githubusercontent.com/4501388/122602415-653a5600-d038-11eb-9c08-ffad1d72ddfb.png">

3 - Click Split button to enter mode (other lines disappear)
![3](https://user-images.githubusercontent.com/4501388/122602453-77b48f80-d038-11eb-9056-7566186bdb10.png)

4 - Select part to detach
![4](https://user-images.githubusercontent.com/4501388/122602484-83a05180-d038-11eb-8cd4-219b7ceb4de1.png)

5 - Finish
![5](https://user-images.githubusercontent.com/4501388/122602650-d24deb80-d038-11eb-9a8b-8740bd7d7f11.png)

**Comment by DaviTeodoro** [comment]
https://github.com/axismaps/levant-carta-next/commit/4a2f980074ca8b8a08bdb8d3c8c256575e827a5f this and
