### ISSUE TITLE
Allow newly drawn feature to be cleared before adding required attributes

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/levantCarta#69]
For cases when a feature is drawn mistakenly. The panel close button would be one way to allow this.

<img width="790" alt="Screen Shot 2021-06-17 at 10 32 57 AM" src="https://user-images.githubusercontent.com/4501388/122428721-c9391d80-cf57-11eb-9b3c-9def099a80d6.png">

**Comment by bcsheesley** [comment]
Closing the "Edit Feature" panel could be a good way to exit editing/drawing modes in general.

**Comment by DaviTeodoro** [comment]
https://github.com/axismaps/levant-carta-next/commit/ec613a8bc25e3856aae7791a22dcd7d2f5a619ca
