### ISSUE TITLE
Can error messages reference language files?

### ISSUE THREAD

**Issue by davidheyman** [axismaps/levantCarta#7]
I like the simplicity of throwing an error and having it appear directly in the UI, but it would be good to reference this through the translation files. Hopefully it is as simple as changing:

```js
callback(new Error('It must be after Start Year'));
```

to:

```js
callback(new Error(errors.startyear));
```

**Comment by DaviTeodoro** [comment]
a6a29313b84b4c33f986c958f3d928c41c1ff8b8 solves it =)
