### ISSUE TITLE
When adding a new feature, hide or disable the attribute input fields

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/levantCarta#70]
- Press "Add a new feature" button
- Try to enter data in the attribute form in the sidebar
- Inputs receive focus, but nothing can be typed or selected

Does a feature need to be drawn before attributes can be entered? If so, a combination of hiding, disabling, and/or user messaging might be needed:

![message](https://user-images.githubusercontent.com/4501388/122432459-f1764b80-cf5a-11eb-867f-352c32fb9c6e.png)

**Comment by DaviTeodoro** [comment]
https://github.com/axismaps/levant-carta-next/commit/1f70fe35647df8997d324ccb75154ac9483e15ce
