### ISSUE TITLE
Cannot clone a feature

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/levantCarta#71]
https://levant-carta-next.vercel.app/

- Select a building
- Press the Clone tool button
- All tool buttons turn gray
- No duplicate feature appears

<img width="649" alt="Screen Shot 2021-06-17 at 11 08 22 AM" src="https://user-images.githubusercontent.com/4501388/122433996-554d4400-cf5c-11eb-92c0-b9c22abe0c6a.png">

**Comment by bcsheesley** [comment]
Update: I think the cloned feature is appearing, but it's exactly on top of the original. What about adding a slight offset to a newly cloned feature so that it's obvious it has been created?

**Comment by DaviTeodoro** [comment]
I think a better approach would clone and also activate the edit mode so the user would see that something actually happened.
If they need a clone of a feature they may also need it to be at the same place.

**Comment by bcsheesley** [comment]
That sounds good to me. I agree, cloning in place is a likely use case.

**Comment by DaviTeodoro** [comment]
https://github.com/axismaps/levant-carta-next/commit/1bef23e2843614e1d74e54db523767f214460f07 also fix
