### ISSUE TITLE
Cannot move features in edit mode

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/levantCarta#72]
https://levant-carta-next.vercel.app/

Individual nodes can be repositioned, but there is no clear way to move entire features.

**Comment by DaviTeodoro** [comment]
This is a restriction of the library (nebula.gl)... I may need to add a "transform mode", much like Photoshop. 
I still trying to figure a way to not do so tho.

**Comment by DaviTeodoro** [comment]
https://github.com/axismaps/levant-carta-next/commit/1bef23e2843614e1d74e54db523767f214460f07 also fix this
