### ISSUE TITLE
Add tooltip hints to cursor when in drawing mode

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/levantCarta#8]
E.g., when using the line tool, tips would go something like, "click to start drawing line", "click to continue drawing line", and "click last point to finish line".

![Screen Shot 2019-11-18 at 2 20 52 PM](https://user-images.githubusercontent.com/4501388/69090702-a73f8800-0a0e-11ea-88cf-ce519bfd64a8.png)

**Comment by DaviTeodoro** [comment]
1c52ffb8136a4f857b921a78aed856436376b876 solves it.
