### ISSUE TITLE
Hide drawing tools in the toolbar that are not applicable to the selected geometry

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/levantCarta#9]
So, when editing lines for example, hide the point and polygon buttons instead of graying them out. I think we'll need the space in the toolbar later...

Tools that are applicable to the selected geometry but not permitted due to current context can still be grayed out, if that makes sense.

**Comment by DaviTeodoro** [comment]
8cd0486ec21b4dbd4fa23414b413a68beeec1a98 solves it
